//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSAPIWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_tbl
    {
        public Company_tbl()
        {
            this.User_tbl = new HashSet<User_tbl>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyContact { get; set; }
        public string CompanyPassword { get; set; }
        public Nullable<int> AllowedUsers { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string PackageType { get; set; }
    
        public virtual ICollection<User_tbl> User_tbl { get; set; }
    }
}
